name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-use/setup-rust@stable
        with:
          toolchain: stable

      - name: Build release binary
        run: cargo build --release

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/asn1smith
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
